# Generated by Django 2.2.9 on 2020-02-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing_slug',
        ),
    ]
