# Generated by Django 2.2.9 on 2020-02-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messgage',
            new_name='message',
        ),
    ]
