# Generated by Django 2.2.9 on 2020-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='listing_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
